### ISSUE TITLE
ab2p.common.css causes breakage on some sites

### ISSUE THREAD

**Issue by wmyrda** [essandess/adblock2privoxy#17]
When sites are visited privoxy is sending to browser info to ask webserver for both `$host.css` and `ab2p.common.css` like in example below
```
192.168.101.10 - - [04/Jul/2018:10:27:31 +0200] "GET /www.wprost.pl/ab2p.css HTTP/1.1" 200 12023
192.168.101.10 - - [04/Jul/2018:10:27:31 +0200] "GET /ab2p.common.css HTTP/1.1" 200 202974
192.168.101.10 - - [04/Jul/2018:10:27:33 +0200] "GET /www.wprost.pl/ab2p.css HTTP/1.1" 200 12023
192.168.101.10 - - [04/Jul/2018:10:27:33 +0200] "GET /ab2p.common.css HTTP/1.1" 200 202974
192.168.101.10 - - [04/Jul/2018:10:27:37 +0200] "GET /emisja.contentstream.pl/ab2p.css HTTP/1.1" 200 11937
```
Problem is than common.css contains all the element hidding entries from all the rulesets which for some sites causes problem as it is blocking more than it should. In this particular example common file has `.cookiespopup` which `pl/wprost/www/ab2p.css` does not have as it actually should not hence no ruleset said it should. Unintended effect is that causes whole website to completely disappear in the browser.

Ideal situation would be that browser asks for ab2p.common.css only if $host.css does not exist. Could that be acomplished by adblock2privoxy, privoxy or the webserver?

**Comment by essandess** [comment]
The CSS `ab2p.common.css` is used for hiding rules common to all domains; therefore, it should always be loaded. This is an issue with inconsistent rule sets, not the rule converter.
