### ISSUE TITLE
disregarding information following $

### ISSUE THREAD

**Issue by wmyrda** [essandess/adblock2privoxy#22]
This one is related to [issue 21 ](https://github.com/essandess/adblock2privoxy/issues/21) and [issue 13](https://github.com/essandess/adblock2privoxy/issues/13).

```
{+client-header-tagger{ab2p-unblock-elem-R1614} \
}
# @@||*$third-party,image,domain=spec-komp.com (onelist.txt: 97062)
/(*PRUNE).*?
```

Converter translates rule to the best of abilities it has at the moment, but in this case that simply means that just about any rules used for blocking domain components would actually get trough due to being whitelisted by this record :(

That probably would not be best solution, but would it not be better to tranlate the rule to `spec-komp.com/(*PRUNE).*?` instead of what is currently done?

**Comment by wmyrda** [comment]
This one comes form https://easylist-downloads.adblockplus.org/advblock.txt

For a workaround as always sed comes to the rescue 
`sed -i -e '/@@||\*\$/s/^/#/' ru_advblock.txt`

**Comment by essandess** [comment]
That appears to be the correct privoxy translation of the supplied rule.
