### ISSUE TITLE
unintended escape characters for [ and ]

### ISSUE THREAD

**Issue by wmyrda** [essandess/adblock2privoxy#28]
I discovered that adding escape characters by the converter before brackets leads to not working rule as privoxy would than expect those characters to be present literally in the link which obviously would not happen

This adblock rule `||mypage.com/dl/201[7-8]-[0-1][0-9]/[3-4][0-9][0-9][0-9]`

is translated to the `^mypage\.com/dl/201\[7-8\]-\[0-1\]\[0-9\]/\[3-4\]\[0-9\]\[0-9\]\[0-9\]`

while it should be `^mypage\.com/dl/201[7-8]-[0-1][0-9]/[3-4][0-9][0-9][0-9]` as only that would catch link as http://mypage.com/dl/2017-10/4014

**Comment by wmyrda** [comment]
Further investigation reveled that `{` and `}` also do not require escape character. I created the patch that deal with that. It works, but better solution is needed hence there were few circumstances where privoxy failed when `[` and `]` characters were not preceded with `\`

```
diff -Naur adblock2privoxy-9999.old/adblock2privoxy/src/PatternConverter.hs adblock2privoxy-9999/adblock2privoxy/src/PatternConverter.hs
--- adblock2privoxy-9999.old/adblock2privoxy/src/PatternConverter.hs    2018-09-11 17:14:36.263280063 +0200
+++ adblock2privoxy-9999/adblock2privoxy/src/PatternConverter.hs        2018-09-11 17:28:15.234003090 +0200
@@ -79,7 +79,7 @@
                                     | c == '*'         = "(*PRUNE).*?"
                                     | c `elem` special = '\\' : [c]
                                     | otherwise        = [c]
-                                    where special = "?$.+[]{}()\\|" -- also ^ and * are special
+                                    where special = "?$.+()\\|" -- also ^ and * are special, []{} are broken with escape character https://github.com/essandess/adblock2privoxy/issues/28
 
 
 hostSeparators :: String
```

```
cat /tmp/privoxy.log |grep Fatal 
2018-09-11 18:08:00.234 7f90b8f460c0 Fatal error: can't load actions file '/etc/privoxy/ab2p.action': line 31695: cannot create URL or TAG pattern from: ^nude-moon\.com/cdn-cgi/pe/bag2\?r[]=http
2018-09-11 18:44:34.562 7ff174ba80c0 Fatal error: can't load actions file '/etc/privoxy/ab2p.action': line 32706: cannot create URL or TAG pattern from: /(?:(*PRUNE).*?/)?newsanons/(*PRUNE).*?\?advert[]=
2018-09-11 18:45:39.828 7f668f03b0c0 Fatal error: can't load actions file '/etc/privoxy/ab2p.action': line 63949: cannot create URL or TAG pattern from: /(?:(*PRUNE).*?/)?cdn-cgi/pe/bag2\?r[]=(*PRUNE).*?eth-pocket\.de
2018-09-11 18:46:50.267 7f08ff5720c0 Fatal error: can't load actions file '/etc/privoxy/ab2p.action': line 281296: cannot create URL or TAG pattern from: ^tidaltv\.com/tpas(*PRUNE).*?\.aspx\?(*PRUNE).*?&rand=[
2018-09-11 18:48:21.794 7f43cb9a40c0 Fatal error: can't load actions file '/etc/privoxy/ab2p.action': line 281297: cannot create URL or TAG pattern from: ^tidaltv\.com/ILogger\.aspx\?(*PRUNE).*?&adId=[
```

So for now only `{` and `}` can be safely treated as those not requiring escape character

**Comment by wmyrda** [comment]
For tens of thousands records I stumbled upon `=[` combination only in the rules related to channel4.com which raises the question if they are properly written
```
@@||innovid.com/iroll/config/*.xml?cb=[$object-subrequest,domain=channel4.com
@@||tidaltv.com/ILogger.aspx?*&adId=[$object-subrequest,domain=channel4.com
@@||tidaltv.com/tpas*.aspx?*&rand=[$object-subrequest,domain=channel4.com
```

Assuming this it right and both `=[` and `[]=` need escape characters below script may be used to workaround the problem before real solution within the converter is found.

Run it only if adblock2privoxy was build with the patch removing treating `[` and `]` as escape chars.
prior to adblock2privoxy uses particular filter
`sed -i -e 's/Id\=\[/Id\=\\[/' -e 's/and\=\[/and\=\\[/' -e 's/cb\=\[/cb\=\\[/' -e 's/\[\]\=/\\[\\]\=/' myfilter.txt`
or after on the resulting file
`sed -i -e 's/Id\=\[/Id\=\\[/' -e 's/and\=\[/and\=\\[/' -e 's/cb\=\[/cb\=\\[/' -e 's/\[\]\=/\\[\\]\=/' ab2p.action`

**Comment by essandess** [comment]
The translation is correct, the rule is wrong is a regular expression is intended. See e.g.
https://adblockplus.org/forum/viewtopic.php?f=23&t=55336

Please upstream this issue.
