### ISSUE TITLE
update filterlist

### ISSUE THREAD

**Issue by KonoromiHimaries** [essandess/adblock2privoxy#30]
last update for 19 Jul 2017
https://github.com/essandess/adblock2privoxy/blob/master/privoxy/ab2p.action

https://github.com/collinbarrett/FilterLists/issues/573

**Comment by essandess** [comment]
Those files are over 20 MB each, and the css directory structure is hundreds of MB. Every update and commit multiples the size of the repo by that much.

GitHub repos are not a great way of hosting these filter lists.

I’m open to suggestions, but the simplest thing to do is just build and run `adblock2privoxy` locally.

**Comment by KonoromiHimaries** [comment]
use ipfs https://github.com/ipfs/ipfs

**Comment by essandess** [comment]
ipfs still needs a server infrastructure to host files.

The filter files depend on user preferences for the easylist/adblock filters chosen.

This is a repo for software to convert easylist to adblock files, not update them host select rule sets. That would be a great project for someone to take up, though.
