### ISSUE TITLE
Content Removal

### ISSUE THREAD

**Issue by legalaxur** [essandess/adblock2privoxy#31]
Dear Sir/Madam,

Our company, AXUR, represents Sicredi  in issues involving the violation of intellectual property and fraud on the Internet.

Sicredi  is the only company authorized to use the trademark SICREDI and owns or licenses numerous trademark registrations worldwide, including, but not limited to the following registration number INPI:814022499,814022499,823823121, 823823130,823823148,823823156    .

The trademarks, logos, words and phrases registered by Sicredi  shall be exclusively used by Sicredi  and any other use by a third party constitutes a trademark infringement.

It has come to our attention that the page attached to this message (below) provides related content (see attached) to the trademark SICREDI without having obtained prior written authorization from Sicredi . By using this trademark, it creates a Likelihood of Confusion between the trademark SICREDI and the content reported.

Furthermore, by misusing the trademark SICREDI, it weakens the ability of brand identification as a single source of research and may lead consumers to believe that there is some association between Sicredi  and the content reported

Official Website: http://www.sicredi.com.br/

Considering the violation of intellectual property rights of Sicredi  on your Github Page, we kindly request that you remove all content available on the attached URL(s) which use the abovementioned trademark without having obtained prior authorization. We therefore are requesting the removal of all content mentioning the trademark "Sicredi" on the link reported below.

In order to avoid a lawsuit from a federal court, please, send confirmation that this email was received along with your guarantee to comply with the requests reported above.

Under penalty of perjury, we affirm that AXUR is authorized to act on behalf of the Sicredi  and this notification is in accordance with International Regulations of Internet and Intellectual Property Offices.

Should you require further information or should you prefer to discuss this issue, please do not hesitate to contact us through the e-mail address listed on the signature of this message.

Sincerely,

AXUR
Legal Team
legal@axur.com

ATTACHMENT:
https://github.com/essandess/adblock2privoxy/blob/master/easylist/malwaredomains_full.txt

**Comment by essandess** [comment]
The inclusion of your client’s publicly registered domain name in a malware blocking list does not constitute a trademark violation.

Your client’s public domain name appears as an easylist block rule in the file https://raw.githubusercontent.com/essandess/adblock2privoxy/master/easylist/malwaredomains_full.txt:
```
||sicredi.com.br.incorpbb.com^
```

**Comment by jedisct1** [comment]
Even more ridiculous is the fact that the purpose of that entry is to prevent accessing a fake website impersonating their client :)
