### ISSUE TITLE
Ad2p run breaks with "Illegal instruction"

### ISSUE THREAD

**Issue by alet** [essandess/adblock2privoxy#35]
On FreeBSD 12.2 ad2p successfully compiling but running ended with:
```
process https://easylist.to/easylist/easyprivacy.txt
load https://easylist.to/easylist/easyprivacy.txt (5 more attempts)...
Illegal instruction

```
The command:
```
adblock2privoxy -p /usr/local/etc/privoxy -w /usr/local/www/css -d 192.168.7.31:8119 -t list.ad2p \
https://easylist.to/easylist/easyprivacy.txt https://easylist.to/easylist/easylist.txt \
https://easylist.to/easylist/fanboy-annoyance.txt https://easylist.to/easylist/fanboy-social.txt \
https://easylist-downloads.adblockplus.org/antiadblockfilters.txt \
https://easylist-downloads.adblockplus.org/malwaredomains_full.txt \
https://raw.githubusercontent.com/ryanbr/fanboy-adblock/master/fanboy-antifacebook.txt \
https://raw.githubusercontent.com/Dawsey21/Lists/master/adblock-list.txt
```

**Comment by essandess** [comment]
The url `https://easylist-downloads.adblockplus.org/malwaredomains_full.txt` doesn’t exist, so `adblock2privoxy` is returning an error:

```bash
wget --max-redirect=0 -S --spider https://easylist-downloads.adblockplus.org/malwaredomains_full.txt 2>&1
```

See the MacPorts bash script here along with this list of easylist downloads for one way to handle this:
* https://github.com/macports/macports-ports/blob/d275a24edbefe7f361f2aa6eb8f59648092058c0/www/adblock2privoxy/Portfile#L123-L131
* https://github.com/macports/macports-ports/blob/master/www/adblock2privoxy/files/adblock2privoxy_blocklist.txt

**Comment by essandess** [comment]
I do not see this issue on macOS.

This call isn't (directly) from any `adblock2privoxy` code, but undoubtedly from one of its Haskell `import`'s. My best guess is that this is used for TLS checks. Lots of apparently related non-`ghc` [issues](https://www.google.com/search?q=openat%28AT_FDCWD%2C%22%2Fdev%2Furandom%22%2CO_RDONLY+%22Inappropriate+ioctl+for+device%22&hl=en&ei=tJqaYMrPK_ax5NoPjMi1cA&oq=openat%28AT_FDCWD%2C%22%2Fdev%2Furandom%22%2CO_RDONLY+%22Inappropriate+ioctl+for+device%22) like this out there. I'd advice to try to isolate which upstream thing is causing this and bump this upstream.
