### ISSUE TITLE
The site https://projects.zubr.me/wiki/adblock2privoxyDownloads does not open

### ISSUE THREAD

**Issue by vladns** [essandess/adblock2privoxy#36]
Actually the subject. And it seems apache2 has stayed in the old configuration.

**Comment by essandess** [comment]
This is a fork of the original site, and I have no control over it.

I use an `nginx` CSS server, so updated `nginx.conf`. If someone posts a PR for an Apache server with TLS, I’ll sanity check it and pull the configuration.
