### ISSUE TITLE
rsync: link_stat "/root/adblock2privoxy*" failed: No such file or directory (2)

### ISSUE THREAD

**Issue by vladns** [essandess/adblock2privoxy#37]
After executing rsync -a ./adblock2privoxy* /usr/local/etc/adblock2privoxy, an error message appears:
`rsync: link_stat "/root/adblock2privoxy*" failed: No such file or directory (2)
`
`rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
`
Commands are performed from root, Ubuntu Server OS.

**Comment by essandess** [comment]
The `rsync` error message says that you're trying to copy a directory that isn't there. Does `./adblock2privoxy*` exist in the directory that you're running `rsync` from?

**Comment by vladns** [comment]
No...

**Comment by essandess** [comment]
> No...

You cannot copy files that aren't there. Please read `man rsync`.

**Comment by vladns** [comment]
How does ./adblock2privoxy appear? If it is "sudo mkdir -p /usr/local/etc/adblock2privoxy" then it is empty after running this command.

**Comment by essandess** [comment]
You must download a release or clone the repo. https://github.com/essandess/adblock2privoxy/releases
