### ISSUE TITLE
css directories and webserver

### ISSUE THREAD

**Issue by K1GP** [essandess/adblock2privoxy#4]
Why not use privoxy's user-manual folder?
Put css files in there then use http://p.p/user-manual/$host.css in filters can do the same job without webserver.

**Comment by essandess** [comment]
The `nginx` webserver is also used as a black hole server for the parent repo [easylist-pac-privoxy](../../easylist-pac-privoxy).

I’d also be concerned about unintended complexity and breakage running both the proxy and blocking server within `privoxy`.
